spring.application.name=prestamos-service
server.port=8086

# MySQL - Usará las variables de entorno de Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/prestamos_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect