spring.application.name=prestamos-service
server.port=8086

# MySQL - USAR EL NOMBRE DEL CONTENEDOR

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/prestamos_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

