spring.application.name=libros-service
server.port=8081

# MongoDB - Configuración local normal
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=libros_db