spring.application.name=multas-service
server.port=8088
# Base de datos exclusiva para multas
spring.datasource.url=jdbc:mysql://localhost:3306/multas_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pn196239839.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true